name: client
description: A new Flutter Boilerplate Example project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  chewie: ^1.3.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flavor: ^2.0.0
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_timer_countdown: ^1.0.5
  freezed_annotation: ^2.2.0
  get_it: 7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.7.0
  loading_overlay: ^0.3.0
  logger: ^1.1.0
  lottie: ^2.1.0
  path: any
  retrofit: ^3.3.1
  shared_preferences: 2.0.0-nullsafety

dev_dependencies:
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.11.0

  #Flutter analyze
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.5.4
  provider: ^6.0.4

  #Network
  retrofit_generator: ^4.2.0

  #State managment
  rxdart: ^0.27.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/wtechLogo.svg"

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/env/.env.prod
    - assets/env/.env.test
    - assets/env/.env.dev
    - assets/env/
    - assets/images/
    - assets/icons/
    - assets/lottie/
